//
//  TXEnumeUtils.h
//  TiexueReader
//
//  Created by 齐宇 on 14-4-14.
//  Copyright (c) 2014年 tiexue. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface TXEnumeUtils : NSObject
// 书单列表类型 客户端定义
typedef NS_ENUM (NSInteger,TXBookListType)
{
    //书城首页
    TX_ENUME_MALL_BOOKLIST_TYPE_RE_TUI = 1,
    TX_ENUME_MALL_BOOKLIST_TYPE_QIANG_TUI,
    TX_ENUME_MALL_BOOKLIST_TYPE_RE_XIAO,
    TX_ENUME_MALL_BOOKLIST_TYPE_JING_DIAN,
    TX_ENUME_MALL_BOOKLIST_TYPE_MIAN_FEI,
    TX_ENUME_MALL_BOOKLIST_TYPE_JUN_SHI,
    TX_ENUME_MALL_BOOKLIST_TYPE_LI_SHI,
    TX_ENUME_MALL_BOOKLIST_TYPE_XIN_SHU,
    TX_ENUME_MALL_BOOKLIST_TYPE_GENG_DUO,
    //书城完本
    TX_ENUME_MALL_BOOKLIST_TYPE_END_TE_HUI = 20,
    TX_ENUME_MALL_BOOKLIST_TYPE_END_MIAN_FEI,
    TX_ENUME_MALL_BOOKLIST_TYPE_END_QUAN_BU,
    //书城排行
    TX_ENUME_MALL_BOOKLIST_TYPE_RANK_DIAN_JI = 30,
    TX_ENUME_MALL_BOOKLIST_TYPE_RANK_RE_XIAO,
    TX_ENUME_MALL_BOOKLIST_TYPE_RANK_GENG_XIN,
    TX_ENUME_MALL_BOOKLIST_TYPE_RANK_JUN_SHI,
    TX_ENUME_MALL_BOOKLIST_TYPE_RANK_LI_SHI,
    TX_ENUME_MALL_BOOKLIST_TYPE_RANK_SHOU_CANG,
    //书城分类
    TX_ENUME_MALL_BOOKLIST_TYPE_KIND_JUNSHI = 40,
    TX_ENUME_MALL_BOOKLIST_TYPE_KIND_LISHI,
    TX_ENUME_MALL_BOOKLIST_TYPE_KIND_XUANHUAN,
    TX_ENUME_MALL_BOOKLIST_TYPE_KIND_XIANXIA,
    TX_ENUME_MALL_BOOKLIST_TYPE_KIND_DUSHI,
    TX_ENUME_MALL_BOOKLIST_TYPE_KIND_QINGGAN,
    TX_ENUME_MALL_BOOKLIST_TYPE_KIND_TUILI,
    TX_ENUME_MALL_BOOKLIST_TYPE_KIND_XUANYI,
    TX_ENUME_MALL_BOOKLIST_TYPE_KIND_DUANPIAN,
    TX_ENUME_MALL_BOOKLIST_TYPE_KIND_CHUBAN
};
//书籍状态枚举
typedef NS_ENUM(NSInteger, TXBookStatus)
{
    TX_BOOK_STATUS_LIANZAI = 1,
    TX_BOOK_STATUS_WANBEN
};

+ (NSString *)getBookListTypeName:(TXBookListType)type;

+ (NSString *)getBookStatusName:(TXBookStatus)status;
@end
